# How to use:
# pip install pre-commit
# pre-commit install
# That's ok!
repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-lint
