# db configuration
dbType: mysql
username: root
password: roothjack
host: 127.0.0.1
port: 3306
schema: deploy_manager
params:
  charset: utf8mb4
  parseTime: True
  loc: Local
autoMigrate: true
logMode: 4
maxIdleConns: 20
maxOpenConns: 0
connMaxLifetime: 0
